data_source: 
  train_data: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_training_set.csv
  test_data: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_test_set.csv

artifacts: 
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv

  model_dir: model_dir
  model_filename: LogisticRegression.model

  reports_dir: reports_dir
  scores: scores.json 