data_source: 

  train_data: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_training_set.csv
  test_data: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_test_set.csv
  skiprows: 20

  s3_source_train: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_training_set.csv
  source_test: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_test_set.csv
  skiprows : 20


database:
  user_name: 'nZwsNGMCBZfOFipzdNMzihNf'
  password: 't9UMQhDvW7YNLr5n+B8a_1uabFpthMkGIkla,tT-uaPxlZ-XsBXGaZ5It7Ph6Qc7f58xNvirLKDc+ZZ9Px_b1,eI-Z24mqp_1Ie+uilUGMmsaj9kcrCKiEUAb.dn4JIk'

artifacts: 
  artifacts_dir: artifacts
  local_data_dirs: local_data_dirs
  local_data_train_file: aps_failure_training_set.csv
  local_data_test_file: aps_failure_test_set.csv
  preprocessed_data_dir: preprocessed_data_dir
  preprocessed_data_file: preprocessed_training_data.csv
  target_column_data_dir: target_column_data_dir
  target_column_data_file: target_column_training_data.csv
  preprocessed_test_file: preprocessed_testing_data.csv
  target_column_testdata_file: target_column_testing_data.csv

  # model_dir: model_dir
  # model_filename: LogisticRegression.model

  reports_dir: reports_dir
  scores: scores.json 














# data_source: 
#   s3_source_train: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_training_set.csv
#   s3_source_test: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_test_set.csv
#   skiprows : 20
# database:
#   user_name : 'nZwsNGMCBZfOFipzdNMzihNf'
#   password: 't9UMQhDvW7YNLr5n+B8a_1uabFpthMkGIkla,tT-uaPxlZ-XsBXGaZ5It7Ph6Qc7f58xNvirLKDc+ZZ9Px_b1,eI-Z24mqp_1Ie+uilUGMmsaj9kcrCKiEUAb.dn4JIk'
# artifacts: 
#   artifacts_dir: artifacts
#   local_data_dirs: local_data_dirs
#   local_data_train_file: aps_failure_training_set.csv
#   local_data_test_file: aps_failure_test_set.csv
#   preprocessed_data_dir: preprocessed_data_dir
#   preprocessed_data_file: preprocessed_training_data.csv
#   target_column_data_dir: target_column_data_dir
#   target_column_data_file: target_column_training_data.csv

#   split_data_dir: split_data_dir
#   train: train.csv
#   test: test.csv

#   model_dir: model_dir
#   model_filename: LogisticRegression.model

#   reports_dir: reports_dir
#   scores: scores.json 