source_download_dirs: https://archive.ics.uci.edu/ml/machine-learning-databases/00421/aps_failure_training_set.csv

local_data_dirs: 
  - data/train
  - data/test  

artifacts: 
  artifacts_dir: artifacts
  raw_local_dir: raw_local_dir
  raw_local_file: data.csv


  

  model_dir: model_dir
  model_filename: LogisticRegression.model

  reports_dir: reports_dir
  scores: scores.json 