base:
  project: Scania-Truck-Failure
  random_state: 42
  test_size: 0.25
  n_components: 90

#standard_scalar:
#  standard_scale_file_path: standard_scalar_object_dir
#  standard_scale_file_name: standard_scaling.pkl

preprocesssing_objects:
  preprocesssing_objects_path: preprocesssing_objects_dir
  standard_scale_file_name: normalizer.pkl
  label_encoding_file_name: label_encoding.pkl
  pca_file_name: pca.pkl
  imputer_file_name: median_imputer.pkl
standard_scalar:
  standard_scale_file_path: standard_scalar_object_dir
  standard_scale_file_name: standard_scaling.pkl
  standard_scale_predfile_name: standard_scaling_pred.pkl
config:
  params: config/params.yaml
  schema_prediction: config/schema_prediction.json
  schema_training: config/schema_training.json

data_download:
  training_directory_path: data/training_batch_files/
  prediction_directory_path: data/Prediction_Batch_files

artifacts:
  training_data:
    # null_value_info_file_path: artifacts/training_data/preprocessing/null_value
    # plots: artifacts/training_data/plots
    scaler_path: artifacts/standard_scalar_object_dir/standard_scaling

  model:
    model_path: artifacts/model_dir/Xg-Boost.pkl

  prediction_data:
    prediction_output_file_path: Prediction_Output_DIR/
    prediction_file_name: Predictions.csv


logs_database:
  database_name: scania_truck_failures
  training_table_name: scania_training
  prediction_table_name: scania_prediction

model_training_thread:
  model_training_thread_table_name: model_training_thread

dataset:
  unwanted_column:
    - cd_000
    - ch_000

target_columns:
  columns:
    - class  